#
# This pipeline needs the following tasks:
#   - git-clone
#   - flake8
#   - nose
#   - buildah (ClusterTask)
#   - openshift-client (ClusterTask)
#
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  workspaces:
    - name: pipeline-workspace

  params:
    - name: repo-url
      description: Git repository URL
    - name: branch
      description: Git branch
      default: main
    - name: build-image
      description: Image name to build and deploy

  tasks:
    # -------------------
    # Clone
    # -------------------
    - name: clone
     taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: pipeline-workspace
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch)

    # -------------------
    # Lint
    # -------------------
    - name: lint
      taskRef:
        name: flake8
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: image
          value: "python:3.9-slim"
        - name: args
          value:
            - "--exit-zero"
            - "--count"
            - "--max-complexity=10"
            - "--max-line-length=127"
            - "--statistics"
      runAfter:
        - clone

    # -------------------
    # Tests
    # -------------------
    - name: tests
      taskRef:
        name: nose
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: database_uri
          value: "sqlite:///test.db"
        - name: args
          value: "-v --with-spec --spec-color"
      runAfter:
        - clone

    # -------------------
    # Build Image
    # -------------------
    - name: build
      taskRef:
        name: buildah
        kind: ClusterTask
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: IMAGE
          value: "$(params.build-image)"
      runAfter:
        - lint
        - tests

    # -------------------
    # Deploy to OpenShift
    # -------------------
    - name: deploy
      workspaces:
        - name: manifest-dir
          workspace: pipeline-workspace
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
        - name: SCRIPT
          value: |
            echo "Updating manifest..."
            sed -i "s|IMAGE_NAME_HERE|$(params.build-image)|g" deploy/deployment.yaml
            cat deploy/deployment.yaml
            echo "Deploying to OpenShift..."
            oc apply -f deploy/
            oc get pods -l app=accounts
      runAfter:
        - build
